# Generated by Django 5.1.5 on 2025-01-28 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
