# Generated by Django 5.1.5 on 2025-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
