# Generated by Django 5.1.5 on 2025-02-01 13:59

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_customuser_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh_expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 13, 59, 19, 547595)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
