# Generated by Django 5.1.5 on 2025-02-01 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_customuser_refresh_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refresh_expire_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
