# Generated by Django 5.1.5 on 2025-02-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_alter_customuser_refresh_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='refresh_expire_time',
            new_name='refresh_start',
        ),
    ]
